name: Deploy to Combell

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 3️⃣ Build project
      - name: Build project
        run: npm run build

      # 4️⃣ Deploy to Combell via FTP
      - name: 🚀 FTP Deploy to Combell
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.didiervanasschecom.webhosting.be
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: dist/
          server-dir: /www/unwind/
          timeout: 60000
          dangerous-clean-slate: true
